pool:
  name: Hosted Ubuntu 1604

variables:
  MONGODBUSER: $(DbUser)
  MONGODBPASSWORD: $(DbPassword)
  MONGODBHOSTNAME: $(DbHostname)
  MONGODBCONNECTIONSTRING: $(DbConnectionString)
  TESTDBUSER: $(DbUser)

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*[Tt]ests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Integration
  inputs:
    command: run
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
